import { Prisma, PrismaClient, TaskPriority, TaskStatus, WorkspaceRole } from "@prisma/client";
import { z } from "zod";
import { WorkspaceError } from "./workspaces.js";

const uuid=z.string().uuid(),dateOnly=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable().optional();
const projectFields={name:z.string().trim().min(2).max(120),description:z.string().trim().max(2000),status:z.enum(["ACTIVE","COMPLETED","ARCHIVED"]),color:z.string().regex(/^#[0-9a-fA-F]{6}$/),start:dateOnly,due:dateOnly,memberIds:z.array(uuid).max(100)};
const projectCreate=z.object({...projectFields,description:projectFields.description.default(""),status:projectFields.status.default("ACTIVE"),memberIds:projectFields.memberIds.default([])});
const projectPatch=z.object({name:projectFields.name.optional(),description:projectFields.description.optional(),status:projectFields.status.optional(),color:projectFields.color.optional(),start:projectFields.start,due:projectFields.due,memberIds:projectFields.memberIds.optional()}).refine(value=>Object.keys(value).length>0);
const taskFields={projectId:uuid,title:z.string().trim().min(2).max(200),description:z.string().trim().max(5000),status:z.enum(["PENDING","IN_PROGRESS","COMPLETED"]),priority:z.enum(["LOW","MEDIUM","HIGH"]),due:dateOnly,assigneeIds:z.array(uuid).min(1).max(20).transform(ids=>[...new Set(ids)])};
const taskCreate=z.object({...taskFields,description:taskFields.description.default(""),status:taskFields.status.default("PENDING"),priority:taskFields.priority.default("MEDIUM")});
const taskPatch=z.object({projectId:taskFields.projectId.optional(),title:taskFields.title.optional(),description:taskFields.description.optional(),status:taskFields.status.optional(),priority:taskFields.priority.optional(),due:taskFields.due,assigneeIds:taskFields.assigneeIds.optional()}).refine(value=>Object.keys(value).length>0);
const taskQuery=z.object({projectId:uuid.optional(),status:z.nativeEnum(TaskStatus).optional(),priority:z.nativeEnum(TaskPriority).optional(),assigneeId:uuid.optional(),from:dateOnly,to:dateOnly,q:z.string().trim().max(200).optional(),mine:z.enum(["true","false"]).optional(),limit:z.coerce.number().int().min(1).max(200).default(200)});
const fail=(code:string,message:string,statusCode=403):never=>{throw new WorkspaceError(code,message,statusCode)};
const atUtc=(value:string|null|undefined)=>value?new Date(`${value}T00:00:00.000Z`):null;
const day=(value:Date|null)=>value?.toISOString().slice(0,10)??"";

export class BusinessService {
  constructor(private readonly prisma:PrismaClient){}

  async projects(actorId:string,workspaceId:string){const id=uuid.parse(workspaceId);await this.member(actorId,id);return Promise.all((await this.prisma.project.findMany({where:{workspaceId:id},include:{members:true,_count:{select:{tasks:true}}},orderBy:{createdAt:"desc"},take:200})).map(row=>this.projectView(row)))}
  async project(actorId:string,workspaceId:string,projectId:string){const wid=uuid.parse(workspaceId),id=uuid.parse(projectId);await this.member(actorId,wid);const row=await this.prisma.project.findFirst({where:{id,workspaceId:wid},include:{members:true,_count:{select:{tasks:true}}}});if(!row)return fail("PROJECT_NOT_FOUND","Projeto não encontrado.",404);return this.projectView(row)}
  async createProject(actorId:string,workspaceId:string,input:unknown){const wid=uuid.parse(workspaceId),data=projectCreate.parse(input);await this.manager(actorId,wid);await this.validMembers(wid,data.memberIds);const row=await this.prisma.$transaction(async tx=>{const created=await tx.project.create({data:{workspaceId:wid,createdById:actorId,name:data.name,description:data.description,status:data.status,color:data.color,startsAt:atUtc(data.start),dueAt:atUtc(data.due),members:{create:data.memberIds.map(userId=>({userId}))}},include:{members:true,_count:{select:{tasks:true}}}});await tx.activity.create({data:{workspaceId:wid,actorId,type:"PROJECT_CREATED",payload:{projectId:created.id,name:created.name}}});return created});return this.projectView(row)}
  async updateProject(actorId:string,workspaceId:string,projectId:string,input:unknown){const wid=uuid.parse(workspaceId),id=uuid.parse(projectId),data=projectPatch.parse(input);await this.manager(actorId,wid);if(data.memberIds)await this.validMembers(wid,data.memberIds);return this.prisma.$transaction(async tx=>{const exists=await tx.project.findFirst({where:{id,workspaceId:wid}});if(!exists)fail("PROJECT_NOT_FOUND","Projeto não encontrado.",404);if(data.memberIds){await tx.projectMember.deleteMany({where:{projectId:id}});await tx.projectMember.createMany({data:data.memberIds.map(userId=>({projectId:id,userId})),skipDuplicates:true})}const row=await tx.project.update({where:{id},data:{name:data.name,description:data.description,status:data.status,color:data.color,startsAt:data.start===undefined?undefined:atUtc(data.start),dueAt:data.due===undefined?undefined:atUtc(data.due)},include:{members:true,_count:{select:{tasks:true}}}});await tx.activity.create({data:{workspaceId:wid,actorId,type:"PROJECT_UPDATED",payload:{projectId:id}}});return this.projectView(row)})}
  async deleteProject(actorId:string,workspaceId:string,projectId:string){const wid=uuid.parse(workspaceId),id=uuid.parse(projectId);await this.manager(actorId,wid);const project=await this.prisma.project.findFirst({where:{id,workspaceId:wid},include:{_count:{select:{tasks:true}}}});if(!project)return fail("PROJECT_NOT_FOUND","Projeto não encontrado.",404);if(project._count.tasks)fail("PROJECT_HAS_TASKS","Remova ou mova as tarefas antes de excluir o projeto.",409);await this.prisma.$transaction([this.prisma.project.delete({where:{id}}),this.prisma.activity.create({data:{workspaceId:wid,actorId,type:"PROJECT_REMOVED",payload:{projectId:id,name:project.name}}})]);return {removed:true}}

  async tasks(actorId:string,workspaceId:string,query:unknown){const wid=uuid.parse(workspaceId);await this.member(actorId,wid);const filters=taskQuery.parse(query);const where:Prisma.TaskWhereInput={workspaceId:wid,projectId:filters.projectId,status:filters.status,priority:filters.priority,dueAt:{...(filters.from?{gte:atUtc(filters.from)!}:{}),...(filters.to?{lte:atUtc(filters.to)!}: {})},...(filters.assigneeId?{assignees:{some:{userId:filters.assigneeId}}}:{}),...(filters.mine==="true"?{assignees:{some:{userId:actorId}}}:{}),...(filters.q?{OR:[{title:{contains:filters.q,mode:"insensitive"}},{description:{contains:filters.q,mode:"insensitive"}},{project:{name:{contains:filters.q,mode:"insensitive"}}}]}:{})};return (await this.prisma.task.findMany({where,include:this.taskInclude,orderBy:{updatedAt:"desc"},take:filters.limit})).map(row=>this.taskView(row))}
  async task(actorId:string,workspaceId:string,taskId:string){const wid=uuid.parse(workspaceId),id=uuid.parse(taskId);await this.member(actorId,wid);const row=await this.prisma.task.findFirst({where:{id,workspaceId:wid},include:this.taskInclude});if(!row)return fail("TASK_NOT_FOUND","Tarefa não encontrada.",404);return this.taskView(row)}
  async createTask(actorId:string,workspaceId:string,input:unknown){const wid=uuid.parse(workspaceId),data=taskCreate.parse(input);await this.member(actorId,wid);await this.validProject(wid,data.projectId);await this.validMembers(wid,data.assigneeIds);const row=await this.prisma.$transaction(async tx=>{const created=await tx.task.create({data:{workspaceId:wid,projectId:data.projectId,createdById:actorId,title:data.title,description:data.description,status:data.status,priority:data.priority,dueAt:atUtc(data.due),completedAt:data.status==="COMPLETED"?new Date():null,assignees:{create:data.assigneeIds.map(userId=>({userId}))}},include:this.taskInclude});await tx.activity.create({data:{workspaceId:wid,actorId,type:"TASK_CREATED",payload:{taskId:created.id,projectId:created.projectId,title:created.title}}});return created});return this.taskView(row)}
  async updateTask(actorId:string,workspaceId:string,taskId:string,input:unknown){const wid=uuid.parse(workspaceId),id=uuid.parse(taskId),data=taskPatch.parse(input),actor=await this.member(actorId,wid);const current=await this.prisma.task.findFirst({where:{id,workspaceId:wid},include:{assignees:true}});if(!current)return fail("TASK_NOT_FOUND","Tarefa não encontrada.",404);const manager=actor.role!=="MEMBER",participates=current.createdById===actorId||current.assignees.some(item=>item.userId===actorId);if(!manager&&!participates)fail("FORBIDDEN","Você só pode editar tarefas criadas ou atribuídas a você.");if(!manager&&(data.projectId||data.priority||data.due!==undefined||data.assigneeIds))fail("FORBIDDEN","Somente administradores alteram projeto, responsáveis, prioridade e prazo.");if(data.projectId)await this.validProject(wid,data.projectId);if(data.assigneeIds)await this.validMembers(wid,data.assigneeIds);return this.prisma.$transaction(async tx=>{if(data.assigneeIds){await tx.taskAssignee.deleteMany({where:{taskId:id}});await tx.taskAssignee.createMany({data:data.assigneeIds.map(userId=>({taskId:id,userId})),skipDuplicates:true})}const row=await tx.task.update({where:{id},data:{projectId:data.projectId,title:data.title,description:data.description,status:data.status,priority:data.priority,dueAt:data.due===undefined?undefined:atUtc(data.due),completedAt:data.status===undefined?undefined:data.status==="COMPLETED"?(current.completedAt??new Date()):null},include:this.taskInclude});const changed=[];if(data.status&&data.status!==current.status)changed.push(data.status==="COMPLETED"?"TASK_COMPLETED":"TASK_STATUS_CHANGED");if(data.priority&&data.priority!==current.priority)changed.push("TASK_PRIORITY_CHANGED");if(data.due!==undefined&&day(current.dueAt)!==(data.due??""))changed.push("TASK_DUE_CHANGED");if(data.assigneeIds)changed.push("TASK_ASSIGNEES_CHANGED");if(!changed.length)changed.push("TASK_UPDATED");await tx.activity.createMany({data:changed.map(type=>({workspaceId:wid,actorId,type,payload:{taskId:id}}))});return this.taskView(row)})}
  async deleteTask(actorId:string,workspaceId:string,taskId:string){const wid=uuid.parse(workspaceId),id=uuid.parse(taskId);await this.manager(actorId,wid);const task=await this.prisma.task.findFirst({where:{id,workspaceId:wid}});if(!task)return fail("TASK_NOT_FOUND","Tarefa não encontrada.",404);await this.prisma.$transaction([this.prisma.task.delete({where:{id}}),this.prisma.activity.create({data:{workspaceId:wid,actorId,type:"TASK_REMOVED",payload:{taskId:id,title:task.title}}})]);return {removed:true}}
  async activities(actorId:string,workspaceId:string,userId?:string){const wid=uuid.parse(workspaceId);await this.member(actorId,wid);const target=userId?uuid.parse(userId):undefined;if(target)await this.member(target,wid,false);const rows=await this.prisma.activity.findMany({where:{workspaceId:wid},include:{actor:{include:{profile:true}}},orderBy:{createdAt:"desc"},take:200});if(!target)return rows.slice(0,50);const taskIds=new Set((await this.prisma.task.findMany({where:{workspaceId:wid,OR:[{createdById:target},{assignees:{some:{userId:target}}}]},select:{id:true}})).map(item=>item.id));return rows.filter(row=>{const payload=row.payload as Record<string,unknown>;return row.actorId===target||payload.userId===target||payload.toUserId===target||typeof payload.taskId==="string"&&taskIds.has(payload.taskId)}).slice(0,50)}

  private taskInclude={assignees:{include:{user:{include:{profile:true}}}},project:{select:{id:true,name:true}}} as const;
  private async member(userId:string,workspaceId:string,requireActive=true){const row=await this.prisma.membership.findUnique({where:{workspaceId_userId:{workspaceId,userId}}});if(!row)return fail("WORKSPACE_NOT_FOUND","Workspace não encontrado.",404);if(requireActive&&row.status!=="ACTIVE")fail("WORKSPACE_BLOCKED","Acesso bloqueado neste workspace.");return row}
  private async manager(userId:string,workspaceId:string){const row=await this.member(userId,workspaceId);if(row.role===WorkspaceRole.MEMBER)fail("FORBIDDEN","Permissão administrativa necessária.");return row}
  private async validProject(workspaceId:string,projectId:string){if(!await this.prisma.project.findFirst({where:{id:projectId,workspaceId},select:{id:true}}))fail("INVALID_PROJECT","Projeto não pertence ao workspace.",400)}
  private async validMembers(workspaceId:string,userIds:string[]){if(!userIds.length)return;const count=await this.prisma.membership.count({where:{workspaceId,userId:{in:[...new Set(userIds)]},status:"ACTIVE"}});if(count!==new Set(userIds).size)fail("INVALID_ASSIGNEE","Responsável ou participante não pertence ao workspace ou está bloqueado.",400)}
  private projectView(row:{id:string;workspaceId:string;createdById:string;name:string;description:string;color:string;status:"ACTIVE"|"COMPLETED"|"ARCHIVED";startsAt:Date|null;dueAt:Date|null;createdAt:Date;updatedAt:Date;members:{userId:string}[];_count:{tasks:number}}){return{id:row.id,workspaceId:row.workspaceId,createdById:row.createdById,name:row.name,description:row.description,color:row.color,status:row.status,start:day(row.startsAt),due:day(row.dueAt),memberIds:row.members.map(item=>item.userId),taskCount:row._count.tasks,createdAt:row.createdAt,updatedAt:row.updatedAt}}
  private taskView(row:{id:string;workspaceId:string;projectId:string;createdById:string;title:string;description:string;status:TaskStatus;priority:TaskPriority;dueAt:Date|null;completedAt:Date|null;createdAt:Date;updatedAt:Date;project:{id:string;name:string};assignees:{userId:string;user:{email:string;profile:{name:string;jobTitle:string|null;avatarKey:string|null}|null}}[]}){return{id:row.id,workspaceId:row.workspaceId,projectId:row.projectId,projectName:row.project.name,createdById:row.createdById,title:row.title,description:row.description,status:row.status,priority:row.priority,due:day(row.dueAt),completedAt:row.completedAt,createdAt:row.createdAt,updatedAt:row.updatedAt,assignees:row.assignees.map(item=>({userId:item.userId,email:item.user.email,name:item.user.profile?.name??"",job:item.user.profile?.jobTitle??null,avatarKey:item.user.profile?.avatarKey??null}))}}
}
