<template>
  <main class="login-shell"><section class="login-brand-panel"><div class="login-brand"><span class="brand-mark"><Check /></span>TaskFlow</div><div class="login-message"><span>Organização que flui</span><h1>Transforme planos em entregas.</h1><p>Centralize tarefas, projetos e colaboração em um espaço simples, bonito e eficiente.</p></div><div class="login-orb one"/><div class="login-orb two"/></section>
  <section class="login-form-side"><form class="login-card" @submit.prevent="submit"><div class="mobile-login-brand"><span class="brand-mark"><Check /></span>TaskFlow</div><p class="login-kicker">BEM-VINDO DE VOLTA</p><h2>Acesse sua conta</h2><p class="login-intro">Entre para continuar organizando seus projetos.</p><label>E-mail<div class="login-input"><Mail/><input v-model="email" type="email" required/></div></label><label>Senha<div class="login-input"><LockKeyhole/><input v-model="password" :type="show?'text':'password'" required/><button type="button" @click="show=!show"><EyeOff v-if="show"/><Eye v-else/></button></div></label><div class="login-options"><label><input v-model="remember" type="checkbox"/>Lembrar de mim</label><button type="button" @click="error='Recuperação disponível em uma próxima versão.'">Esqueci minha senha</button></div><div v-if="error" class="login-error">{{error}}</div><button class="login-submit">Entrar <span>→</span></button><div class="demo-access"><div class="demo-title"><span>ACESSO DE DEMONSTRAÇÃO</span><i/></div><p>Escolha um perfil para explorar o projeto.</p><div><button type="button" @click="enterDemo('Administrador')"><ShieldCheck/><span><strong>Administrador</strong><small>Kayque Milhome</small></span></button><button type="button" @click="enterDemo('Membro')"><UserRound/><span><strong>Membro</strong><small>Marina Costa</small></span></button></div></div><p class="signup-copy">Não possui uma conta? <RouterLink to="/cadastro">Criar conta</RouterLink></p></form></section></main>
</template>
<script setup lang="ts">
import {ref} from "vue";import{useRouter,RouterLink}from"vue-router";import{Check,Eye,EyeOff,LockKeyhole,Mail,ShieldCheck,UserRound}from"lucide-vue-next";import{useAuthStore}from"../stores/auth";import{browserDataRepository as repository,storageKeys}from"../services/storage";
const auth=useAuthStore(),router=useRouter(),email=ref(repository.readText(storageKeys.rememberEmail)),password=ref(""),show=ref(false),remember=ref(Boolean(email.value)),error=ref("");
async function submit(){error.value="";try{await auth.login(email.value,password.value);if(remember.value)repository.writeText(storageKeys.rememberEmail,email.value);else repository.remove(storageKeys.rememberEmail);router.replace("/dashboard")}catch(e){error.value=auth.error||((e as Error).message)}}
async function enterDemo(role:"Administrador"|"Membro"){const credentials=role==="Administrador"?{email:"kayque@taskflow.demo",password:"123456"}:{email:"marina@taskflow.demo",password:"123456"};email.value=credentials.email;password.value=credentials.password;await submit()}
</script>
