<template>
<main class="app-shell">
  <aside class="sidebar" :class="{open:sidebar}">
    <button class="mobile-close" @click="sidebar=false"><X/></button>
    <button class="brand" @click="go('/dashboard')"><span class="brand-mark"><Check/></span>TaskFlow</button>
    <nav><p class="nav-label workspace-label">WORKSPACE<small>{{store.currentWorkspace?.name}}</small></p>
      <button v-for="item in primaryNav" :key="item.path" class="nav-item" :class="{active:isActive(item.path)}" @click="go(item.path)"><component :is="item.icon"/>{{item.label}}<span v-if="item.path==='/tarefas'" class="nav-count">{{counts.pending}}</span></button>
      <template v-if="store.admin"><p class="nav-label second">GESTÃO</p><button v-for="item in adminNav" :key="item.path" class="nav-item" :class="{active:isActive(item.path)}" @click="go(item.path)"><component :is="item.icon"/>{{item.label}}</button></template>
      <button class="nav-item" :class="{active:isActive('/configuracoes')}" @click="go('/configuracoes')"><Settings/>Configurações</button>
    </nav>
    <div class="upgrade motivational"><Rocket/><strong>Grandes resultados começam com pequenas tarefas.</strong></div>
    <div class="profile popover-anchor"><button class="profile-main" @click.stop="profileMenu=!profileMenu"><Avatar :member="currentMember"/><span><strong>{{auth.user?.name}}</strong><small>{{auth.user?.job}}</small></span></button><button class="sidebar-more" @click.stop="profileMenu=!profileMenu"><MoreHorizontal/></button>
      <div v-if="profileMenu" class="profile-pop profile-actions"><button @click="openProfile"><UserRound/>Meu perfil</button><button @click="go('/configuracoes')"><Settings/>Configurações</button><button @click="workspaceModal=true;profileMenu=false"><FolderKanban/>Trocar workspace</button><button class="logout-action" @click="logout"><LogOut/>Sair</button></div>
    </div>
  </aside>
  <section class="workspace"><header class="topbar"><button class="menu-btn" @click="sidebar=true"><Menu/></button><label class="global-search"><Search/><input v-model="query" @focus="route.path!='/tarefas'&&go('/tarefas')" placeholder="Buscar tarefas e projetos..."/><kbd>⌘ K</kbd></label><div class="top-actions"><button title="Ajuda" @click="toast='Explore os cards, projetos e indicadores.'"><CircleHelp/></button><button class="notification" title="Notificações" @click.stop="notifications=!notifications"><Bell/><i v-if="counts.pending"/></button><button v-if="store.admin" class="notification invite-shortcut" title="Convidar pessoas" @click="inviteModal=true"><Send/></button></div><div v-if="notifications" class="notification-pop"><strong>Notificações</strong><p>Você possui {{counts.pending}} tarefa(s) pendente(s).</p></div></header>
  <div class="content">
    <Dashboard :name="auth.user?.name||''" v-if="route.path==='/dashboard'" :tasks="store.visibleTasks" :projects="store.visibleProjects" :counts="counts" :weekly="store.prefs.weekly" @navigate="go" @task="editTask"/>
    <Tasks v-else-if="route.path==='/tarefas'" :tasks="filteredTasks" :projects="store.projects" :members="store.members" :admin="store.admin" v-model:status="status" v-model:priority="priority" @task="editTask"/>
    <Projects v-else-if="route.path==='/projetos'" :projects="store.visibleProjects" :tasks="store.visibleTasks" :admin="store.admin" @open="id=>go('/projetos/'+id)" @add="newProject"/>
    <ProjectDetail v-else-if="route.path.startsWith('/projetos/')" :project="selectedProject" :tasks="store.visibleTasks" :members="store.members" :admin="store.admin" @back="go('/projetos')" @task="editTask" @add="()=>editTask(undefined,selectedProject?.id)"/>
    <Calendar v-else-if="route.path==='/calendario'" :tasks="store.visibleTasks" :projects="store.projects" @task="editTask"/>
    <Team v-else-if="route.path==='/equipe'" :members="store.members" :tasks="store.tasks" @add="inviteModal=true" @open="id=>go('/equipe/'+id+'/atividades')" @edit="editMember" @toggle="toggleMember" @remove="removeMember"/>
    <MemberActivities v-else-if="route.path.includes('/atividades')" :member="selectedMember" :tasks="store.tasks" :projects="store.projects" @back="go('/equipe')" @task="editTask"/>
    <Reports v-else-if="route.path==='/relatorios'" :tasks="store.tasks" :projects="store.projects"/>
    <Preferences v-else-if="route.path==='/configuracoes'" :prefs="store.prefs" @save="savePrefs"/>
  </div></section>

  <TaskDialog v-if="taskModal" :task="editingTask" :project-id="defaultProject" :projects="store.projects" :members="store.members" :admin="store.admin" :member-id="store.session!.memberId" @close="taskModal=false" @save="saveTask" @remove="removeTask"/>
  <ProjectDialog v-if="projectModal" :members="store.members" @close="projectModal=false" @save="saveProject"/>
  <InviteDialog v-if="inviteModal" :workspace="store.currentWorkspace?.name||'Workspace'" @close="inviteModal=false" @send="sendInvite"/>
  <WorkspaceDialog v-if="workspaceModal" :workspaces="availableWorkspaces" :current="store.session!.workspaceId" @close="workspaceModal=false" @select="switchWorkspace" @create="createWorkspace"/>
  <ProfileDialog v-if="profileModal" :account="currentAccount" :member="currentMember" :role="store.session!.role" @close="profileModal=false" @save="saveProfile"/>
  <MemberDialog v-if="memberModal" :member="editingMember!" @close="memberModal=false" @save="saveMember"/>
  <div v-if="toast" class="toast"><Check/>{{toast}}</div>
</main>
</template>

<script setup lang="ts">
import{computed,onBeforeUnmount,onMounted,ref,watch}from"vue";import{useRoute,useRouter}from"vue-router";import{Bell,CalendarDays,Check,CircleHelp,FileBarChart,FolderKanban,LayoutDashboard,LogOut,Menu,MoreHorizontal,Rocket,Search,Send,Settings,UserRound,Users,X}from"lucide-vue-next";
import{useTaskFlowStore,type Member,type Prefs,type Project,type Status,type Priority,type Task}from"../stores/taskflow";import{useAuthStore}from"../stores/auth";
import Avatar from"../components/Avatar.vue";import Dashboard from"../components/Dashboard.vue";import Tasks from"../components/Tasks.vue";import Projects from"../components/Projects.vue";import ProjectDetail from"../components/ProjectDetail.vue";import Calendar from"../components/Calendar.vue";import Team from"../components/Team.vue";import MemberActivities from"../components/MemberActivities.vue";import Reports from"../components/Reports.vue";import Preferences from"../components/Preferences.vue";import TaskDialog from"../components/TaskDialog.vue";import ProjectDialog from"../components/ProjectDialog.vue";import InviteDialog from"../components/InviteDialog.vue";import WorkspaceDialog from"../components/WorkspaceDialog.vue";import ProfileDialog from"../components/ProfileDialog.vue";import MemberDialog from"../components/MemberDialog.vue";
const store=useTaskFlowStore(),auth=useAuthStore(),router=useRouter(),route=useRoute(),query=ref(""),status=ref<"Todas"|Status>((route.query.status==="concluida"?"Concluída":route.query.status==="andamento"?"Em andamento":route.query.status==="pendente"?"Pendente":"Todas")),priority=ref<"Todas"|Priority>("Todas"),sidebar=ref(false),profileMenu=ref(false),notifications=ref(false),toast=ref(""),taskModal=ref(false),projectModal=ref(false),inviteModal=ref(false),workspaceModal=ref(false),profileModal=ref(false),memberModal=ref(false),editingTask=ref<Task>(),editingMember=ref<Member>(),defaultProject=ref(1);
if(auth.user)store.adoptAuthenticatedUser(auth.user);
const primaryNav=[{path:"/dashboard",label:"Dashboard",icon:LayoutDashboard},{path:"/tarefas",label:"Minhas tarefas",icon:Check},{path:"/projetos",label:"Projetos",icon:FolderKanban},{path:"/calendario",label:"Calendário",icon:CalendarDays}],adminNav=[{path:"/equipe",label:"Equipe",icon:Users},{path:"/relatorios",label:"Relatórios",icon:FileBarChart}];
const counts=computed(()=>({all:store.visibleTasks.length,pending:store.visibleTasks.filter(t=>t.status==="Pendente").length,active:store.visibleTasks.filter(t=>t.status==="Em andamento").length,done:store.visibleTasks.filter(t=>t.status==="Concluída").length}));
const filteredTasks=computed(()=>store.visibleTasks.filter(t=>(status.value==="Todas"||t.status===status.value)&&(priority.value==="Todas"||t.priority===priority.value)&&(`${t.title} ${store.projects.find(p=>p.id===t.projectId)?.name}`).toLowerCase().includes(query.value.toLowerCase())));
const selectedProject=computed(()=>store.projects.find(p=>p.id===Number(route.params.id))),selectedMember=computed(()=>store.members.find(m=>m.id===Number(route.params.id))),currentMember=computed(()=>store.members.find(m=>m.id===store.session?.memberId)),currentAccount=computed(()=>store.accounts.find(a=>a.id===store.session?.accountId));
const availableWorkspaces=computed(()=>store.memberships.filter(m=>m.accountId===store.session?.accountId).map(m=>({...m,workspace:store.workspaces.find(w=>w.id===m.workspaceId)!})));
function go(path:string){router.push(path);sidebar.value=false;profileMenu.value=false}function isActive(path:string){return route.path===path||path==="/projetos"&&route.path.startsWith("/projetos/")||path==="/equipe"&&route.path.startsWith("/equipe/")}
function editTask(task?:Task,pid?:number){if(!store.admin&&!task)return show("Somente administradores podem criar tarefas.");editingTask.value=task;defaultProject.value=pid||task?.projectId||store.projects[0]?.id||1;taskModal.value=true}function saveTask(task:Task){store.saveTask(task);taskModal.value=false;show(editingTask.value?"Tarefa atualizada.":"Tarefa criada.")}function removeTask(id:number){store.removeTask(id);taskModal.value=false;show("Tarefa excluída.")}
function newProject(){projectModal.value=true}function saveProject(p:Project){store.saveProject(p);projectModal.value=false;show("Projeto criado.")}function editMember(m:Member){editingMember.value={...m};memberModal.value=true}function saveMember(m:Member){store.saveMember(m);memberModal.value=false;show("Membro atualizado.")}function toggleMember(m:Member){store.saveMember({...m,blocked:!m.blocked});show(m.blocked?"Acesso desbloqueado.":"Acesso bloqueado.")}function removeMember(m:Member){if(confirm(`Remover ${m.name} do workspace?`)){store.removeMember(m.id);show("Membro removido.")}}
function savePrefs(p:Prefs){store.prefs={...p};show("✓ Configurações salvas com sucesso.")}function sendInvite(){inviteModal.value=false;show("Convite registrado para demonstração.")}function switchWorkspace(id:number){store.switchWorkspace(id);workspaceModal.value=false;go("/dashboard");show("Workspace alterado.")}function createWorkspace(name:string){store.createWorkspace(name);workspaceModal.value=false;go("/dashboard");show("Workspace criado.")}function openProfile(){profileMenu.value=false;profileModal.value=true}async function saveProfile(data:{name:string;job:string;avatar?:string}){try{const user=await auth.updateProfile(data.name,data.job,data.avatar);store.adoptAuthenticatedUser(user);profileModal.value=false;show("Perfil atualizado.")}catch{show("Não foi possível atualizar o perfil.")}}async function logout(){try{await auth.logout()}catch{/* Limpeza local também após falha da API. */}finally{store.logout();await router.replace("/login")}}
let timer:number;function show(message:string){toast.value=message;clearTimeout(timer);timer=window.setTimeout(()=>toast.value="",2600)}function closeMenus(){profileMenu.value=false;notifications.value=false}onMounted(()=>document.addEventListener("click",closeMenus));onBeforeUnmount(()=>document.removeEventListener("click",closeMenus));watch(()=>route.query.status,v=>status.value=v==="concluida"?"Concluída":v==="andamento"?"Em andamento":v==="pendente"?"Pendente":"Todas");
</script>
