<template>
<main class="app-shell">
  <aside class="sidebar" :class="{open:sidebar}">
    <button class="mobile-close" @click="sidebar=false"><X/></button>
    <button class="brand" @click="go('/dashboard')"><span class="brand-mark"><Check/></span>TaskFlow</button>
    <nav><p class="nav-label workspace-label">WORKSPACE<small>{{workspaces.active?.name||'Nenhum workspace'}}</small></p>
      <button v-for="item in primaryNav" :key="item.path" class="nav-item" :class="{active:isActive(item.path)}" @click="go(item.path)"><component :is="item.icon"/>{{item.label}}<span v-if="item.path==='/tarefas'" class="nav-count">{{counts.pending}}</span></button>
      <template v-if="workspaces.active"><p class="nav-label second">GESTÃO</p><button v-for="item in adminNav.filter(item=>item.path==='/equipe'||workspaces.canManage)" :key="item.path" class="nav-item" :class="{active:isActive(item.path)}" @click="go(item.path)"><component :is="item.icon"/>{{item.label}}</button></template>
      <button class="nav-item" :class="{active:isActive('/configuracoes')}" @click="go('/configuracoes')"><Settings/>Configurações</button>
    </nav>
    <div class="upgrade motivational"><Rocket/><strong>Grandes resultados começam com pequenas tarefas.</strong></div>
    <div class="profile popover-anchor"><button class="profile-main" @click.stop="profileMenu=!profileMenu"><Avatar :member="currentMember"/><span><strong>{{auth.user?.name}}</strong><small>{{auth.user?.job}}</small></span></button><button class="sidebar-more" @click.stop="profileMenu=!profileMenu"><MoreHorizontal/></button>
      <div v-if="profileMenu" class="profile-pop profile-actions"><button @click="openProfile"><UserRound/>Meu perfil</button><button @click="go('/configuracoes')"><Settings/>Configurações</button><button @click="workspaceModal=true;profileMenu=false"><FolderKanban/>Trocar workspace</button><button class="logout-action" @click="logout"><LogOut/>Sair</button></div>
    </div>
  </aside>
  <section class="workspace"><header class="topbar"><button class="menu-btn" @click="sidebar=true"><Menu/></button><label class="global-search"><Search/><input v-model="query" @focus="route.path!='/tarefas'&&go('/tarefas')" placeholder="Buscar tarefas e projetos..."/><kbd>⌘ K</kbd></label><div class="top-actions"><button title="Ajuda" @click="toast='Explore os cards, projetos e indicadores.'"><CircleHelp/></button><button class="notification" title="Notificações" @click.stop="notifications=!notifications"><Bell/><i v-if="counts.pending"/></button><button v-if="workspaces.canManage" class="notification invite-shortcut" title="Convidar pessoas" @click="openInvite"><Send/></button></div><div v-if="notifications" class="notification-pop"><strong>Notificações</strong><p>Você possui {{counts.pending}} tarefa(s) pendente(s).</p></div></header>
  <div class="content">
    <div v-if="workspaces.state==='loading'" class="panel empty">Carregando workspaces...</div>
    <div v-else-if="workspaces.state==='error'" class="panel empty">{{workspaces.error}} <button class="text-btn" @click="workspaces.load()">Tentar novamente</button></div>
    <div v-else-if="!workspaces.active" class="panel empty">Nenhum workspace acessível. <button class="text-btn" @click="workspaceModal=true">Criar workspace</button></div>
    <div v-else-if="business.state==='loading'" class="panel empty">Carregando projetos e tarefas...</div>
    <div v-else-if="business.state==='error'" class="panel empty">{{business.error}} <button class="text-btn" @click="reloadBusiness">Tentar novamente</button></div>
    <Dashboard :name="auth.user?.name||''" v-else-if="route.path==='/dashboard'" :tasks="visibleTasks" :projects="visibleProjects" :members="store.members" :activities="business.activities" :counts="counts" :weekly="store.prefs.weekly" @navigate="go" @task="editTask"/>
    <Tasks v-else-if="route.path==='/tarefas'" :tasks="filteredTasks" :projects="business.projects" :members="store.members" :admin="store.admin" v-model:status="status" v-model:priority="priority" @task="editTask"/>
    <Projects v-else-if="route.path==='/projetos'" :projects="visibleProjects" :tasks="visibleTasks" :admin="store.admin" @open="id=>go('/projetos/'+id)" @add="newProject"/>
    <ProjectDetail v-else-if="route.path.startsWith('/projetos/')" :project="selectedProject" :tasks="visibleTasks" :members="store.members" :admin="store.admin" @back="go('/projetos')" @task="editTask" @add="()=>editTask(undefined,selectedProject?.id)" @edit="editProject"/>
    <Calendar v-else-if="route.path==='/calendario'" :tasks="visibleTasks" :projects="business.projects" @task="editTask"/>
    <Team v-else-if="route.path==='/equipe'" :members="store.members" :tasks="business.tasks" :can-manage="workspaces.canManage" :current-role="workspaces.active?.role||'MEMBER'" :current-user-id="auth.user?.id||''" @add="openInvite" @open="id=>go('/equipe/'+id+'/atividades')" @edit="editMember" @toggle="toggleMember" @remove="removeMember" @transfer="transferOwnership"/>
    <MemberActivities v-else-if="route.path.includes('/atividades')" :member="selectedMember" :tasks="business.tasks" :projects="business.projects" :activities="business.activities" @back="go('/equipe')" @task="editTask"/>
    <Reports v-else-if="route.path==='/relatorios'" :tasks="business.tasks" :projects="business.projects" :members="store.members"/>
    <Preferences v-else-if="route.path==='/configuracoes'" :prefs="store.prefs" @save="savePrefs"/>
  </div></section>

  <TaskDialog v-if="taskModal" :task="editingTask" :project-id="defaultProject" :projects="business.projects" :members="store.members" :admin="store.admin" :member-id="store.session!.memberId" @close="taskModal=false" @save="saveTask" @remove="removeTask"/>
  <ProjectDialog v-if="projectModal" :members="store.members" :project="editingProject" @close="projectModal=false" @save="saveProject" @remove="removeProject"/>
  <InviteDialog v-if="inviteModal" :workspace="workspaces.active?.name||'Workspace'" :link="inviteLink" :invitations="workspaces.invitations" @close="inviteModal=false" @send="sendInvite" @regenerate="regenerateInvite" @revoke="revokeCurrentInvite" @revoke-id="revokeInvite"/>
  <WorkspaceDialog v-if="workspaceModal" :workspaces="workspaces.list" :current="workspaces.activeId" :current-role="workspaces.active?.role" @close="workspaceModal=false" @select="switchWorkspace" @create="createWorkspace" @rename="renameWorkspace"/>
  <ProfileDialog v-if="profileModal" :account="currentAccount" :member="currentMember" :role="store.session?.role||'Membro'" @close="profileModal=false" @save="saveProfile"/>
  <MemberDialog v-if="memberModal" :member="editingMember!" @close="memberModal=false" @save="saveMember"/>
  <div v-if="toast" class="toast"><Check/>{{toast}}</div>
</main>
</template>

<script setup lang="ts">
import{computed,onBeforeUnmount,onMounted,ref,watch}from"vue";import{useRoute,useRouter}from"vue-router";import{Bell,CalendarDays,Check,CircleHelp,FileBarChart,FolderKanban,LayoutDashboard,LogOut,Menu,MoreHorizontal,Rocket,Search,Send,Settings,UserRound,Users,X}from"lucide-vue-next";
import{useTaskFlowStore,type Member,type Prefs,type Project,type Status,type Priority,type Task}from"../stores/taskflow";import{useAuthStore}from"../stores/auth";import{useWorkspacesStore}from"../stores/workspaces";import{useBusinessStore}from"../stores/business";
import Avatar from"../components/Avatar.vue";import Dashboard from"../components/Dashboard.vue";import Tasks from"../components/Tasks.vue";import Projects from"../components/Projects.vue";import ProjectDetail from"../components/ProjectDetail.vue";import Calendar from"../components/Calendar.vue";import Team from"../components/Team.vue";import MemberActivities from"../components/MemberActivities.vue";import Reports from"../components/Reports.vue";import Preferences from"../components/Preferences.vue";import TaskDialog from"../components/TaskDialog.vue";import ProjectDialog from"../components/ProjectDialog.vue";import InviteDialog from"../components/InviteDialog.vue";import WorkspaceDialog from"../components/WorkspaceDialog.vue";import ProfileDialog from"../components/ProfileDialog.vue";import MemberDialog from"../components/MemberDialog.vue";
const store=useTaskFlowStore(),auth=useAuthStore(),workspaces=useWorkspacesStore(),business=useBusinessStore(),router=useRouter(),route=useRoute(),query=ref(""),status=ref<"Todas"|Status>((route.query.status==="concluida"?"Concluída":route.query.status==="andamento"?"Em andamento":route.query.status==="pendente"?"Pendente":"Todas")),priority=ref<"Todas"|Priority>("Todas"),sidebar=ref(false),profileMenu=ref(false),notifications=ref(false),toast=ref(""),taskModal=ref(false),projectModal=ref(false),inviteModal=ref(false),workspaceModal=ref(false),profileModal=ref(false),memberModal=ref(false),editingTask=ref<Task>(),editingProject=ref<Project>(),editingMember=ref<Member>(),defaultProject=ref(1),inviteLink=ref(""),inviteId=ref(""),inviteInput=ref<{email:string;role:"ADMIN"|"MEMBER";workspaceJob:string}|null>(null);
watch([()=>workspaces.activeId,()=>workspaces.members,()=>auth.user],async()=>{if(auth.user&&workspaces.active){store.adoptRemoteWorkspace(auth.user,workspaces.active,workspaces.members);if(business.workspaceId!==workspaces.active.id)await business.load(workspaces.active.id).catch(()=>undefined)}else{store.logout();business.clear()}},{immediate:true});
const primaryNav=[{path:"/dashboard",label:"Dashboard",icon:LayoutDashboard},{path:"/tarefas",label:"Minhas tarefas",icon:Check},{path:"/projetos",label:"Projetos",icon:FolderKanban},{path:"/calendario",label:"Calendário",icon:CalendarDays}],adminNav=[{path:"/equipe",label:"Equipe",icon:Users},{path:"/relatorios",label:"Relatórios",icon:FileBarChart}];
const visibleTasks=computed(()=>store.admin?business.tasks:business.tasks.filter(task=>task.assigneeUserIds?.includes(auth.user?.id||""))),visibleProjects=computed(()=>store.admin?business.projects:business.projects.filter(project=>project.memberUserIds?.includes(auth.user?.id||"")||business.tasks.some(task=>task.projectId===project.id&&task.assigneeUserIds?.includes(auth.user?.id||""))));
const counts=computed(()=>({all:visibleTasks.value.length,pending:visibleTasks.value.filter(t=>t.status==="Pendente").length,active:visibleTasks.value.filter(t=>t.status==="Em andamento").length,done:visibleTasks.value.filter(t=>t.status==="Concluída").length}));
const filteredTasks=computed(()=>visibleTasks.value.filter(t=>(status.value==="Todas"||t.status===status.value)&&(priority.value==="Todas"||t.priority===priority.value)&&(`${t.title} ${business.projects.find(p=>p.id===t.projectId)?.name}`).toLowerCase().includes(query.value.toLowerCase())));
const selectedProject=computed(()=>business.projects.find(p=>p.id===Number(route.params.id))),selectedMember=computed(()=>store.members.find(m=>m.id===Number(route.params.id))),currentMember=computed(()=>store.members.find(m=>m.id===store.session?.memberId)),currentAccount=computed(()=>store.accounts.find(a=>a.id===store.session?.accountId)||{id:0,name:auth.user?.name||"",email:auth.user?.email||"",job:auth.user?.job||"",avatar:auth.user?.avatarKey||undefined,initials:auth.user?.name?.slice(0,2).toUpperCase()||"",password:""});
function go(path:string){router.push(path);sidebar.value=false;profileMenu.value=false}function isActive(path:string){return route.path===path||path==="/projetos"&&route.path.startsWith("/projetos/")||path==="/equipe"&&route.path.startsWith("/equipe/")}
function editTask(task?:Task,pid?:number){editingTask.value=task;defaultProject.value=pid||task?.projectId||business.projects[0]?.id||1;taskModal.value=true}async function saveTask(task:Task){try{const assignee=store.members.find(member=>member.id===task.assigneeId);await business.saveTask({...task,projectRemoteId:business.projects.find(project=>project.id===task.projectId)?.remoteId,assigneeUserIds:assignee?.membershipId?[assignee.membershipId]:task.assigneeUserIds??[]});taskModal.value=false;show(editingTask.value?"Tarefa atualizada.":"Tarefa criada.")}catch(value){show(errorMessage(value))}}async function removeTask(id:number){const task=business.tasks.find(item=>item.id===id);if(!task||!confirm(`Excluir a tarefa ${task.title}?`))return;try{await business.deleteTask(task);taskModal.value=false;show("Tarefa excluída.")}catch(value){show(errorMessage(value))}}
function newProject(){editingProject.value=undefined;projectModal.value=true}function editProject(project:Project){editingProject.value=project;projectModal.value=true}async function saveProject(p:Project){try{await business.saveProject({...p,memberUserIds:p.members.map(id=>store.members.find(member=>member.id===id)?.membershipId).filter((id):id is string=>Boolean(id))});projectModal.value=false;show(editingProject.value?"Projeto atualizado.":"Projeto criado.")}catch(value){show(errorMessage(value))}}async function removeProject(){if(!editingProject.value||!confirm('Excluir este projeto? A exclusão será impedida enquanto houver tarefas.'))return;try{await business.deleteProject(editingProject.value);projectModal.value=false;go('/projetos');show('Projeto excluído.')}catch(value){show(errorMessage(value))}}function editMember(m:Member){editingMember.value={...m};memberModal.value=true}
async function saveMember(data:{workspaceJob:string;role:"Administrador"|"Membro"}){if(!editingMember.value?.membershipId)return;try{await workspaces.editMember(editingMember.value.membershipId,{workspaceJob:data.workspaceJob||null,role:data.role==="Administrador"?"ADMIN":"MEMBER"});memberModal.value=false;show("Membro atualizado.")}catch(value){show(errorMessage(value))}}
async function toggleMember(m:Member){if(!m.membershipId)return;try{await workspaces.editMember(m.membershipId,{status:m.blocked?"ACTIVE":"BLOCKED"});show(m.blocked?"Acesso desbloqueado.":"Acesso bloqueado.")}catch(value){show(errorMessage(value))}}
async function removeMember(m:Member){if(!m.membershipId||!confirm(`Remover ${m.name} do workspace?`))return;try{await workspaces.removeMember(m.membershipId);show("Membro removido do workspace.")}catch(value){show(errorMessage(value))}}
async function transferOwnership(m:Member){if(!m.membershipId||!confirm(`Transferir a propriedade para ${m.name}? Você passará a administrador.`))return;try{await workspaces.transfer(m.membershipId);show("Propriedade transferida.")}catch(value){show(errorMessage(value))}}
function savePrefs(p:Prefs){store.prefs={...p};show("✓ Configurações salvas com sucesso.")}
async function openInvite(){inviteLink.value="";inviteId.value="";inviteModal.value=true;profileMenu.value=false;try{await workspaces.loadInvitations()}catch(value){show(errorMessage(value))}}
async function sendInvite(data:{email:string;job:string;role:string}){const input={email:data.email,workspaceJob:data.job,role:data.role==="Administrador"?"ADMIN" as const:"MEMBER" as const};try{const invitation=await workspaces.createInvitation(input);inviteInput.value=input;inviteLink.value=invitation.link||"";inviteId.value=invitation.id;show("Convite gerado. Copie o link para compartilhar.")}catch(value){show(errorMessage(value))}}
async function revokeInvite(id:string){try{await workspaces.revokeInvitation(id);if(id===inviteId.value){inviteId.value="";inviteLink.value=""}show("Convite revogado.")}catch(value){show(errorMessage(value))}}
async function revokeCurrentInvite(){if(inviteId.value)await revokeInvite(inviteId.value)}
async function regenerateInvite(){if(!inviteInput.value||!inviteId.value)return;try{await workspaces.revokeInvitation(inviteId.value);const invitation=await workspaces.createInvitation(inviteInput.value);inviteId.value=invitation.id;inviteLink.value=invitation.link||"";show("Novo link gerado.")}catch(value){show(errorMessage(value))}}
async function switchWorkspace(id:string){try{await workspaces.select(id);workspaceModal.value=false;go("/dashboard");show("Workspace alterado.")}catch(value){show(errorMessage(value));await workspaces.load().catch(()=>undefined)}}
async function createWorkspace(name:string){try{await workspaces.create(name);workspaceModal.value=false;go("/dashboard");show("Workspace criado.")}catch(value){show(errorMessage(value))}}
async function renameWorkspace(name:string){try{await workspaces.update(name);workspaceModal.value=false;show("Workspace atualizado.")}catch(value){show(errorMessage(value))}}
function openProfile(){profileMenu.value=false;profileModal.value=true}
async function saveProfile(data:{name:string;job:string;avatar?:string}){try{const user=await auth.updateProfile(data.name,data.job,data.avatar);if(workspaces.active){await workspaces.loadMembers();store.adoptRemoteWorkspace(user,workspaces.active,workspaces.members)}profileModal.value=false;show("Perfil atualizado.")}catch(value){show(errorMessage(value))}}
async function reloadBusiness(){if(workspaces.activeId)await business.load(workspaces.activeId).catch(()=>undefined)}
async function logout(){try{await auth.logout()}catch{/* Limpeza local também após falha da API. */}finally{workspaces.clear();business.clear();store.logout();await router.replace("/login")}}
function errorMessage(value:unknown){return value instanceof Error?value.message:"Não foi possível concluir a operação."}
let timer:number;function show(message:string){toast.value=message;clearTimeout(timer);timer=window.setTimeout(()=>toast.value="",2600)}function closeMenus(){profileMenu.value=false;notifications.value=false}function closeOnEscape(event:globalThis.KeyboardEvent){if(event.key==="Escape"){closeMenus();inviteModal.value=false;workspaceModal.value=false;memberModal.value=false;profileModal.value=false}}onMounted(()=>{document.addEventListener("click",closeMenus);document.addEventListener("keydown",closeOnEscape)});onBeforeUnmount(()=>{document.removeEventListener("click",closeMenus);document.removeEventListener("keydown",closeOnEscape)});watch(()=>route.query.status,v=>status.value=v==="concluida"?"Concluída":v==="andamento"?"Em andamento":v==="pendente"?"Pendente":"Todas");
watch(()=>route.path,()=>{if(route.path.includes("/atividades")&&selectedMember.value?.membershipId)business.loadActivities(selectedMember.value.membershipId).catch(()=>undefined);else if(business.workspaceId)business.loadActivities().catch(()=>undefined)});
</script>
