import { computed, ref } from "vue";
import { defineStore } from "pinia";
import { apiRequest, ApiError } from "../services/api.js";
import type { Project, Task } from "../domain/models.js";
import { legacyMemberId } from "./taskflow.js";

interface ProjectApi {id:string;name:string;description:string;color:string;status:"ACTIVE"|"COMPLETED"|"ARCHIVED";start:string;due:string;memberIds:string[];createdAt:string;updatedAt:string}
interface TaskApi {id:string;projectId:string;createdById:string;title:string;description:string;status:"PENDING"|"IN_PROGRESS"|"COMPLETED";priority:"LOW"|"MEDIUM"|"HIGH";due:string;completedAt:string|null;createdAt:string;updatedAt:string;assignees:{userId:string;email:string}[]}
export interface ActivityRecord {id:string;actorId:string|null;type:string;payload:Record<string,unknown>;createdAt:string;actor:{profile:{name:string}|null}|null}
const numberId=(value:string)=>Math.abs([...value].reduce((hash,char)=>(hash*31+char.charCodeAt(0))|0,11))||11;
const statusToUi={PENDING:"Pendente",IN_PROGRESS:"Em andamento",COMPLETED:"Concluída"} as const;
const statusToApi={Pendente:"PENDING","Em andamento":"IN_PROGRESS",Concluída:"COMPLETED"} as const;
const priorityToUi={LOW:"Baixa",MEDIUM:"Média",HIGH:"Alta"} as const;
const priorityToApi={Baixa:"LOW",Média:"MEDIUM",Alta:"HIGH"} as const;

export const useBusinessStore=defineStore("business",()=>{
  const projects=ref<Project[]>([]),tasks=ref<Task[]>([]),activities=ref<ActivityRecord[]>([]),workspaceId=ref<string|null>(null);
  const state=ref<"idle"|"loading"|"ready"|"error">("idle"),error=ref(""),requestVersion=ref(0);
  const failure=(value:unknown)=>value instanceof ApiError?value.message:"Não foi possível carregar projetos e tarefas.";
  const projectRemote=(id:number)=>projects.value.find(item=>item.id===id)?.remoteId;
  const projectLocal=(id:string)=>projects.value.find(item=>item.remoteId===id)?.id??numberId(id);
  const mapProject=(item:ProjectApi):Project=>({id:numberId(item.id),remoteId:item.id,name:item.name,description:item.description,start:item.start,due:item.due,members:item.memberIds.map(id=>legacyMemberId(id,"")),memberUserIds:item.memberIds,color:item.color,status:item.status});
  const mapTask=(item:TaskApi):Task=>({id:numberId(item.id),remoteId:item.id,title:item.title,description:item.description,projectId:projectLocal(item.projectId),projectRemoteId:item.projectId,due:item.due,status:statusToUi[item.status],priority:priorityToUi[item.priority],assigneeId:item.assignees[0]?legacyMemberId(item.assignees[0].userId,item.assignees[0].email):0,assigneeUserIds:item.assignees.map(value=>value.userId),creatorId:item.createdById,createdAt:item.createdAt,updatedAt:item.updatedAt,completedAt:item.completedAt});
  async function load(id:string){const version=++requestVersion.value;workspaceId.value=id;state.value="loading";error.value="";try{const [projectRows,taskRows,activityRows]=await Promise.all([apiRequest<ProjectApi[]>(`/workspaces/${id}/projects`),apiRequest<TaskApi[]>(`/workspaces/${id}/tasks`),apiRequest<ActivityRecord[]>(`/workspaces/${id}/activities`)]);if(version!==requestVersion.value||workspaceId.value!==id)return;projects.value=projectRows.map(mapProject);tasks.value=taskRows.map(mapTask);activities.value=activityRows;state.value="ready"}catch(value){if(version!==requestVersion.value)return;state.value="error";error.value=failure(value);throw value}}
  async function saveProject(project:Project){if(!workspaceId.value)throw new Error("Selecione um workspace.");const body={name:project.name,description:project.description,color:project.color,status:project.status??"ACTIVE",start:project.start||null,due:project.due||null,memberIds:project.memberUserIds??[]};const row=project.remoteId?await apiRequest<ProjectApi>(`/workspaces/${workspaceId.value}/projects/${project.remoteId}`,{method:"PATCH",body:JSON.stringify(body)}):await apiRequest<ProjectApi>(`/workspaces/${workspaceId.value}/projects`,{method:"POST",body:JSON.stringify(body)});const mapped=mapProject(row),index=projects.value.findIndex(item=>item.remoteId===row.id);if(index<0)projects.value.unshift(mapped);else projects.value[index]=mapped;return mapped}
  async function deleteProject(project:Project){if(!workspaceId.value||!project.remoteId)return;await apiRequest(`/workspaces/${workspaceId.value}/projects/${project.remoteId}`,{method:"DELETE"});projects.value=projects.value.filter(item=>item.remoteId!==project.remoteId)}
  async function saveTask(task:Task){if(!workspaceId.value)throw new Error("Selecione um workspace.");const projectId=task.projectRemoteId??projectRemote(task.projectId);if(!projectId)throw new Error("Projeto inválido.");const full={projectId,title:task.title,description:task.description,status:statusToApi[task.status],priority:priorityToApi[task.priority],due:task.due||null,assigneeIds:task.assigneeUserIds??[]};let body:Partial<typeof full>=full;if(task.remoteId){const current=tasks.value.find(item=>item.remoteId===task.remoteId);body={};if(!current||current.projectRemoteId!==projectId)body.projectId=projectId;if(!current||current.title!==task.title)body.title=task.title;if(!current||current.description!==task.description)body.description=task.description;if(!current||current.status!==task.status)body.status=full.status;if(!current||current.priority!==task.priority)body.priority=full.priority;if(!current||current.due!==task.due)body.due=full.due;const before=current?.assigneeUserIds??[],after=full.assigneeIds;if(before.length!==after.length||before.some(id=>!after.includes(id)))body.assigneeIds=after}const row=task.remoteId?await apiRequest<TaskApi>(`/workspaces/${workspaceId.value}/tasks/${task.remoteId}`,{method:"PATCH",body:JSON.stringify(body)}):await apiRequest<TaskApi>(`/workspaces/${workspaceId.value}/tasks`,{method:"POST",body:JSON.stringify(body)});const mapped=mapTask(row),index=tasks.value.findIndex(item=>item.remoteId===row.id);if(index<0)tasks.value.unshift(mapped);else tasks.value[index]=mapped;await loadActivities();return mapped}
  async function deleteTask(task:Task){if(!workspaceId.value||!task.remoteId)return;await apiRequest(`/workspaces/${workspaceId.value}/tasks/${task.remoteId}`,{method:"DELETE"});tasks.value=tasks.value.filter(item=>item.remoteId!==task.remoteId);await loadActivities()}
  async function loadActivities(userId?:string){if(!workspaceId.value)return;activities.value=await apiRequest<ActivityRecord[]>(`/workspaces/${workspaceId.value}/activities${userId?`?userId=${encodeURIComponent(userId)}`:""}`)}
  function clear(){requestVersion.value++;workspaceId.value=null;projects.value=[];tasks.value=[];activities.value=[];state.value="idle";error.value=""}
  const dashboard=computed(()=>({all:tasks.value.length,pending:tasks.value.filter(item=>item.status==="Pendente").length,active:tasks.value.filter(item=>item.status==="Em andamento").length,done:tasks.value.filter(item=>item.status==="Concluída").length}));
  const reports=computed(()=>({status:{pending:dashboard.value.pending,active:dashboard.value.active,done:dashboard.value.done},priority:{high:tasks.value.filter(item=>item.priority==="Alta").length,medium:tasks.value.filter(item=>item.priority==="Média").length,low:tasks.value.filter(item=>item.priority==="Baixa").length},completion:dashboard.value.all?Math.round(dashboard.value.done/dashboard.value.all*100):0}));
  const projectProgress=(projectId:number)=>{const related=tasks.value.filter(item=>item.projectId===projectId),done=related.filter(item=>item.status==="Concluída").length;return related.length?Math.round(done/related.length*100):0};
  const tasksOn=(date:string)=>tasks.value.filter(item=>item.due===date);
  return {projects,tasks,activities,workspaceId,state,error,dashboard,reports,projectProgress,tasksOn,load,saveProject,deleteProject,saveTask,deleteTask,loadActivities,clear};
});
